src/Authorization/Roles/SalesAdminRole.php
src/Authorization/Roles/SalesManagerRole.php
src/Authorization/Roles/SalesPersonRole.php

CRM authorization privileges updated

CRM authorization privileges updated

---

src/Authorization/Roles/SalesManagerRole.php

Sales manager role updated

---

src/Authorization/Roles/SalesAdminRole.php

Sales admin role updated

---

src/Services/RiskManagement/RiskManagementService.php

Risk management updated

---

src/Http/Requests/IdealCustomerProfiles/IdealCustomerProfilesCreateRequest.php
src/Services/IdealCustomerProfilesService.php

ICP creation changed

---

src/Http/Transformers/AbstractTransformers/AbstractOpportunitiesTransformer.php

Abstract opportunity transformer fix

Abstract opportunity transformer fix

---

src/Actions/Accounts/DisableService.php
src/Actions/Accounts/EnableService.php

Enable & disable services are fixed

Enable & disable services are fixed

---

src/Database/Models/AccountsPerspective.php
src/Http/Transformers/AbstractTransformers/AbstractAccountsPerspectiveTransformer.php

Accounts perspective is updated, added 3 new fields

Accounts perspective is updated, added 3 new fields

---

src/Authorization/Roles/SalesManagerRole.php
src/Database/Filters/AccountUsersPerspectiveQueryFilter.php
src/Database/Filters/AccountsPerspectiveQueryFilter.php
src/Database/Filters/AccountsQueryFilter.php
src/Database/Filters/CallsQueryFilter.php
src/Database/Filters/EmailsQueryFilter.php
src/Database/Filters/IdealCustomerProfilesPerspectiveQueryFilter.php
src/Database/Filters/IdealCustomerProfilesQueryFilter.php
src/Database/Filters/MeetingsQueryFilter.php
src/Database/Filters/NotesQueryFilter.php
src/Database/Filters/OpportunitiesQueryFilter.php
src/Database/Filters/ProjectsQueryFilter.php
src/Database/Filters/QuotesQueryFilter.php
src/Database/Filters/TasksQueryFilter.php
src/Database/Filters/UsersPerspectiveQueryFilter.php
src/Database/Filters/UsersPerspectivesQueryFilter.php
src/Database/Filters/UsersQueryFilter.php

Like changed to ilike

---

src/Database/Filters/OpportunitiesPerspectiveQueryFilter.php
src/Database/Filters/OpportunitiesQueryFilter.php
src/Helpers/CrmHelper.php
src/Http/Requests/Opportunities/OpportunitiesCreateRequest.php
src/Http/Transformers/AbstractTransformers/AbstractOpportunitiesPerspectiveTransformer.php
src/Http/Transformers/AbstractTransformers/AbstractOpportunitiesTransformer.php
src/Services/AbstractServices/AbstractOpportunitiesPerspectiveService.php
src/Services/AbstractServices/AbstractOpportunitiesService.php
src/Services/OpportunitiesService.php
src/Services/QuotesService.php

Added new helper, bugifxes about ideal customer is finished

Added new helper, bugifxes about ideal customer is finished

---

src/Actions/Accounts/CreateOpportunity.php
src/Actions/Accounts/WatchAccount.php
src/Database/Models/Industries.php
src/Database/Models/Offerings.php
src/Helpers/CrmHelper.php

CrmHelper, and models updated

---

src/Http/Transformers/AbstractTransformers/AbstractOpportunitiesPerspectiveTransformer.php

Quote lines are added to roles

Quote lines are added to roles

---

src/Actions/QuoteItems/ValidateQuoteItem.php
src/Actions/Quotes/RecalculateQuote.php

Quote actions updated

---

src/Database/Filters/OpportunitiesPerspectiveQueryFilter.php
src/Database/Filters/OpportunitiesQueryFilter.php
src/Http/Transformers/AbstractTransformers/AbstractOpportunitiesPerspectiveTransformer.php
src/Http/Transformers/AbstractTransformers/AbstractOpportunitiesTransformer.php

[Ideal customer profile class name fixed](https://github.com/nextdeveloper-nl/crm/commit/b822fea10fe53be17a6e6ce146938f89cb86ab7d)

Ideal customer profile class name fixed

---

src/Authorization/Roles/SalesAdminRole.php
src/Authorization/Roles/SalesManagerRole.php
src/Authorization/Roles/SalesPersonRole.php

[Authorization role is fixed to delete quote items](https://github.com/nextdeveloper-nl/crm/commit/ddef0f3a45c0721294f050186887ca17cc14bc86)

Authorization role is fixed to delete quote items

---

src/Actions/Quotes/RecalculateQuote.php

Recalculate quote is updated

---

src/Actions/Accounts/DisableAccount.php
src/Database/Models/Accounts.php
src/Database/Models/UsersPerspective.php
src/Helpers/CrmHelper.php
src/Services/AbstractServices/AbstractAccountsService.php

Disable account is added

---

src/Services/AbstractServices/AbstractAccountManagersService.php
src/Services/AbstractServices/AbstractAccountsPerspectiveService.php
src/Services/AbstractServices/AbstractAccountsService.php
src/Services/AbstractServices/AbstractCallsService.php
src/Services/AbstractServices/AbstractEmailsService.php
src/Services/AbstractServices/AbstractIdealCustomerProfilesPerspectiveService.php
src/Services/AbstractServices/AbstractIdealCustomerProfilesService.php
src/Services/AbstractServices/AbstractIndustriesService.php
src/Services/AbstractServices/AbstractMeetingsService.php
src/Services/AbstractServices/AbstractNotesService.php
src/Services/AbstractServices/AbstractOfferingsService.php
src/Services/AbstractServices/AbstractOpportunitiesPerspectiveService.php
src/Services/AbstractServices/AbstractOpportunitiesService.php
src/Services/AbstractServices/AbstractProjectsService.php
src/Services/AbstractServices/AbstractQuoteItemsPerspectiveService.php
src/Services/AbstractServices/AbstractQuoteItemsService.php
src/Services/AbstractServices/AbstractQuoteLinesPerspectiveService.php
src/Services/AbstractServices/AbstractQuoteLinesService.php
src/Services/AbstractServices/AbstractQuotesPerspectiveService.php
src/Services/AbstractServices/AbstractQuotesService.php
src/Services/AbstractServices/AbstractTasksService.php
src/Services/AbstractServices/AbstractUserManagersService.php
src/Services/AbstractServices/AbstractUsersPerspectiveService.php
src/Services/AbstractServices/AbstractUsersService.php

Pagination is fixed

---

src/Authorization/Roles/SalesAdminRole.php
src/Authorization/Roles/SalesManagerRole.php
src/Authorization/Roles/SalesPersonRole.php

Authorization roles updated

---

src/Http/Transformers/QuotesPerspectiveTransformer.php
src/Http/Transformers/QuotesTransformer.php

[CRM Quotes updated](https://github.com/nextdeveloper-nl/crm/commit/422dee7a335483c7ff46925061ad8aec3883b80a)

CRM Quotes updated

---

src/Actions/Quotes/RecalculateQuote.php
src/Services/QuoteItemsService.php

[Quote recalculation fixed](https://github.com/nextdeveloper-nl/crm/commit/6e1ac7f2a3aed1065171b3a98bf45a6b0c3ee95e)

Quote recalculation fixed

---

src/Services/QuoteItemsService.php

[Quote recalculation added to create and delete](https://github.com/nextdeveloper-nl/crm/commit/adcaa1b046455a4c196a4a80d9bc2b1e9cafb32e)
[Quote recalculation added for update](https://github.com/nextdeveloper-nl/crm/commit/e71705c5815b20e6647dd4c3097397b52ae603ab)

Quote recalculation added for create, update and delete

---

src/Http/Requests/Campaigns/CampaignsCreateRequest.php
src/Services/AbstractServices/AbstractUserManagersService.php
src/Services/UsersService.php

[Campaign create request is updated, some requireds are removed](https://github.com/nextdeveloper-nl/crm/commit/531ba73e8d0b23122eafdfa3b28509296c35c148)

Campaign create request is updated, some requireds are removed

---

src/Database/Models/IdealCustomerProfiles.php
src/Services/AbstractServices/AbstractIdealCustomerProfilesService.php
src/Services/IdealCustomerProfilesService.php

Ideal customer profile updated

Ideal customer profile updated

---

src/Database/Models/IdealCustomerProfiles.php
src/Http/Transformers/AbstractTransformers/AbstractIdealCustomerProfilesTransformer.php
src/Services/IdealCustomerProfilesService.php

Ideal customer profiles updated

Ideal customer profiles updated

---

src/Database/Models/TargetUsers.php
src/Helpers/CrmHelper.php

Throw error when user is not found

Throw error when user is not found

---

src/Database/Filters/AccountUsersPerspectiveQueryFilter.php
src/Database/Filters/AccountsPerspectiveQueryFilter.php
src/Database/Filters/AccountsQueryFilter.php
src/Database/Filters/CallsQueryFilter.php
src/Database/Filters/CampaignsQueryFilter.php
src/Database/Filters/EmailTemplatesQueryFilter.php
src/Database/Filters/IdealCustomerProfilesPerspectiveQueryFilter.php
src/Database/Filters/IdealCustomerProfilesQueryFilter.php
src/Database/Filters/IndustriesQueryFilter.php
src/Database/Filters/MeetingsQueryFilter.php
src/Database/Filters/NotesQueryFilter.php
src/Database/Filters/OfferingsQueryFilter.php
src/Database/Filters/OpportunitiesPerspectiveQueryFilter.php
src/Database/Filters/OpportunitiesQueryFilter.php
src/Database/Filters/ProjectsQueryFilter.php
src/Database/Filters/QuoteItemsPerspectiveQueryFilter.php
src/Database/Filters/QuoteLinesPerspectiveQueryFilter.php
src/Database/Filters/QuotesPerspectiveQueryFilter.php
src/Database/Filters/QuotesQueryFilter.php
src/Database/Filters/RegulatoryCompliancesQueryFilter.php
src/Database/Filters/SectorFocusQueryFilter.php
src/Database/Filters/TargetUsersPerspectiveQueryFilter.php
src/Database/Filters/TargetsQueryFilter.php
src/Database/Filters/TasksQueryFilter.php
src/Database/Filters/TechnologiesQueryFilter.php
src/Database/Filters/UsersPerspectiveQueryFilter.php
src/Database/Filters/UsersQueryFilter.php

Search changed to insensitive case

Search changed to insensitive case

---

src/Actions/Quotes/ConvertQuoteToInvoice.php
src/Database/Models/Quotes.php

new column added `is_converted` boolean, please add to prod DB too please

Add action to convert quotes to invoices and update Quotes model
